apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k3s-test
  template:
    metadata:
      labels:
        app: k3s-test
    spec:
      containers:
        - name: k3s-test
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
