apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-webapp2
  template:
    metadata:
      labels:
        app: my-webapp2
    spec:
      containers:
        - name: my-webapp2
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-webapp-service
spec:
  selector:
    app: my-webapp2
  ports:
    - port: 80
      targetPort: 8080
